const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
  const VwHotelTarifaCompleta = sequelize.define('VwHotelTarifaCompleta', {
    id_hotel: {
      type: DataTypes.STRING(40),
      primaryKey: true
    },
    nombre: DataTypes.STRING,
    id_cadena: DataTypes.INTEGER,
    correo: DataTypes.STRING,
    telefono: DataTypes.STRING,
    rfc: DataTypes.STRING,
    razon_social: DataTypes.STRING,
    direccion: DataTypes.STRING,
    latitud: DataTypes.STRING,
    longitud: DataTypes.STRING,
    convenio: DataTypes.TEXT,
    descripcion: DataTypes.TEXT,
    calificacion: DataTypes.FLOAT,
    tipo_hospedaje: DataTypes.STRING,
    cuenta_de_deposito: DataTypes.STRING,
    Estado: DataTypes.STRING,
    Ciudad_Zona: DataTypes.STRING,
    NoktosQ: DataTypes.BIGINT,
    NoktosQQ: DataTypes.BIGINT,
    MenoresEdad: DataTypes.STRING,
    PaxExtraPersona: DataTypes.STRING,
    DesayunoIncluido: DataTypes.STRING,
    DesayunoComentarios: DataTypes.STRING,
    DesayunoPrecioPorPersona: DataTypes.STRING,
    tiene_transportacion: DataTypes.STRING,
    Transportacion: DataTypes.TEXT,
    TransportacionComentarios: DataTypes.TEXT,
    acepta_mascotas: DataTypes.STRING,
    mascotas: DataTypes.TEXT,
    salones: DataTypes.TEXT,
    URLImagenHotel: DataTypes.TEXT,
    URLImagenHotelQ: DataTypes.TEXT,
    URLImagenHotelQQ: DataTypes.TEXT,
    Activo: DataTypes.TINYINT,
    Comentarios: DataTypes.TEXT,
    Id_Sepomex: DataTypes.INTEGER,
    CodigoPostal: DataTypes.STRING,
    Id_hotel_excel: DataTypes.INTEGER,
    Colonia: DataTypes.STRING,
    tipo_negociacion: DataTypes.STRING,
    vigencia_convenio: DataTypes.DATE,
    hay_convenio: DataTypes.STRING,
    comentario_vigencia: DataTypes.TEXT,
    tipo_pago: DataTypes.STRING,
    disponibilidad_precio: DataTypes.TEXT,
    contacto_convenio: DataTypes.TEXT,
    contacto_recepcion: DataTypes.TEXT,
    iva: DataTypes.DECIMAL(5, 2),
    ish: DataTypes.DECIMAL(5, 2),
    otros_impuestos: DataTypes.DECIMAL(12, 2),
    otros_impuestos_porcentaje: DataTypes.DECIMAL(5, 2),
    comentario_pago: DataTypes.TEXT,
    precio_sencilla: DataTypes.DECIMAL(12, 2),
    costo_sencilla: DataTypes.DECIMAL(12, 2),
    desayuno_sencilla: DataTypes.STRING,
    precio_doble: DataTypes.DECIMAL(12, 2),
    costo_doble: DataTypes.DECIMAL(12, 2),
    precio_persona_extra: DataTypes.DECIMAL(12, 2),
    desayuno_doble: DataTypes.STRING,
    pais: DataTypes.STRING,
    score_operaciones: DataTypes.INTEGER
  }, {
    tableName: 'vw_hoteles_tarifas_completa',
    timestamps: false
  });

  return VwHotelTarifaCompleta;
};
